package com.ar.cp.taller.model.entity;
// Generated 19/07/2021 17:46:47 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Mantenimiento generated by hbm2java
 */
@Entity
@Table(name="mantenimiento"
    ,schema="public"
)
public class Mantenimiento  implements java.io.Serializable {


     private int id;
     private Vehiculo vehiculo;
     private String descripcion;
     private String fecha;

    public Mantenimiento() {
    }

    public Mantenimiento(int id, Vehiculo vehiculo, String descripcion, String fecha) {
       this.id = id;
       this.vehiculo = vehiculo;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehiculoid", nullable=false)
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }

    
    @Column(name="descripcion", nullable=false, length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="fecha", nullable=false, length=30)
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


