package com.ar.cp.taller.model.entity;
// Generated 19/07/2021 17:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name="marca"
    ,schema="public"
)
public class Marca  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Set<Modelo> modelos = new HashSet<Modelo>(0);

    public Marca() {
    }

	
    public Marca(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Marca(int id, String nombre, Set<Modelo> modelos) {
       this.id = id;
       this.nombre = nombre;
       this.modelos = modelos;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="marca")
    public Set<Modelo> getModelos() {
        return this.modelos;
    }
    
    public void setModelos(Set<Modelo> modelos) {
        this.modelos = modelos;
    }




}


