package com.ar.cp.taller.model.entity;
// Generated 19/07/2021 17:46:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name="vehiculo"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames="patente") 
)
public class Vehiculo  implements java.io.Serializable {


     private int id;
     private Modelo modelo;
     private String descripcion;
     private String patente;
     private String numerochasis;
     private String numeromotor;
     private Set<Mantenimiento> mantenimientos = new HashSet<Mantenimiento>(0);

    public Vehiculo() {
    }

	
    public Vehiculo(int id, Modelo modelo, String descripcion, String patente) {
        this.id = id;
        this.modelo = modelo;
        this.descripcion = descripcion;
        this.patente = patente;
    }
    public Vehiculo(int id, Modelo modelo, String descripcion, String patente, String numerochasis, String numeromotor, Set<Mantenimiento> mantenimientos) {
       this.id = id;
       this.modelo = modelo;
       this.descripcion = descripcion;
       this.patente = patente;
       this.numerochasis = numerochasis;
       this.numeromotor = numeromotor;
       this.mantenimientos = mantenimientos;
    }
   
    @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modeloid", nullable=false)
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }

    
    @Column(name="descripcion", nullable=false, length=250)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="patente", unique=true, nullable=false, length=10)
    public String getPatente() {
        return this.patente;
    }
    
    public void setPatente(String patente) {
        this.patente = patente;
    }

    
    @Column(name="numerochasis", length=100)
    public String getNumerochasis() {
        return this.numerochasis;
    }
    
    public void setNumerochasis(String numerochasis) {
        this.numerochasis = numerochasis;
    }

    
    @Column(name="numeromotor", length=100)
    public String getNumeromotor() {
        return this.numeromotor;
    }
    
    public void setNumeromotor(String numeromotor) {
        this.numeromotor = numeromotor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vehiculo")
    public Set<Mantenimiento> getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set<Mantenimiento> mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


